# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2418873ecf9c392bad5bf4c3fac2c5387fe87ac87b61831b1253da5b00ffe39aa7dce069aefc8d8e7b3122b6a2ace210ecb396eaf9e1a92a0496858139d21619

test:
  secret_key_base: 3501ec5cb73462d481a24e344c69f18312ff06d5f760d57b27fc1244ce7c1ac582db515f0ef9a03948050c7787e73851659df6d8c96421e41418983faf28b7c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
